<table width="780" border="0" cellspacing="0" cellpadding="0">
      <tr>
        
    <td colspan="5"><img src="images/top.jpg" width="780" height="114"></td>
        </tr>
      <tr>
        <td colspan="5"><table width="780"  border="0" cellspacing="0" cellpadding="2">
          <tr>
            <td width="6" rowspan="3" background="images/bg1.gif"></td>
            <td height="20" align="center" bgcolor="#460000" class="txt2"><a href="index.asp">首页</a>｜　<a href="jj.asp">中心简介</a>　｜　<a href="list.asp?classid=3">最新动态</a>　｜　<a href="list.asp?classid=4">中心成果</a>　｜　<a href="list.asp?classid=5">宣传思想工作</a>　｜　<a href="list.asp?classid=6">重要文献</a>　｜　<a href="lingdao.asp">领导文库</a>　｜<a href="list2.asp?classid=8">专家&特邀研究员</a></td>
          </tr>
          <tr>
            <td height="1"></td>
          </tr>
          <tr>
            <td height="20" align="center" bgcolor="#460000" class="txt2"><a href="list.asp?classid=9">邓小平理论研究</a>　｜　<a href="list.asp?classid=10">“三个代表”研究</a>　｜　<a href="list.asp?classid=12">学者文库</a>　｜　<a href="list.asp?classid=11">网络课堂</a>　｜　<a href="list.asp?classid=13">关注之窗</a>　｜　<a href="list.asp?classid=14">发展风采</a>　｜　<a href="list.asp?classid=15">今日山东</a></td>
          </tr>
        </table></td>
        </tr>
    </table>