<html>
<head>
<title>登陆失败！</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta http-equiv="refresh" content="2;URL=login.asp">
<style type="text/css">
<!--
a:visited{text-transform: none; text-decoration: none; font-style: normal; font-weight: normal; font-variant: normal; color: #000000}
a:hover{text-decoration:underline; color: #FF3333}
a:link{text-transform: none; text-decoration: none; font-weight: normal; font-variant: normal; color: #000000}
.p9 { font-size: 9pt; line-height: 13pt; text-decoration: none}
td { font-size: 9pt; line-height: 13pt; text-decoration: none}
-->
</style>
</head>
<body>
<p>&nbsp;</p>
<table width="348" border="1" align="center" cellpadding="0" cellspacing="0" bordercolorlight="#C0C0C0" bordercolordark="#FFFFFF">
  <tr class="p9"> 
    <td width="338" height="21" align="center" background="pic/h3.gif"><strong><font color="#FFFFFF" size="+1">登陆失败！</font></strong></td>
  </tr>
  <tr align="center" class="p9"> 
    <td>&nbsp;</td>
  </tr>
  <tr class="p9"> 
    <td height="17" align="center"><a href="login.asp">很抱歉，你登陆失败。可能是你的用户名或密码错误！</a></td>
  </tr>
  <tr> 
    <td height="18" align="center" class="p9">请核实你的用户名和密码点击自己重新登陆</td>
  </tr>
  <tr> 
    <td height="18" align="center" class="p9"><a href="login.asp" class="p9">如果你不想等待，请点击这里重新登陆</a></td>
  </tr>
  <tr> 
    <td height="18" align="center">&nbsp;</td>
  </tr>
</table>
</body>
</html>
