<html>
<head>
<title>登陆成功！</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta http-equiv="refresh" content="2;URL=index.asp">
<style type="text/css">
<!--
a:visited{text-transform: none; text-decoration: none; font-style: normal; font-weight: normal; font-variant: normal; color: #000000}
a:hover{text-decoration:underline; color: #FF3333}
a:link{text-transform: none; text-decoration: none; font-weight: normal; font-variant: normal; color: #000000}
.p9 { font-size: 9pt; line-height: 13pt; text-decoration: none}
-->
</style>
</head>
<body>
<p>&nbsp;</p>
<table width="348" border="1" align="center" cellpadding="0" cellspacing="0" bordercolorlight="#C0C0C0" bordercolordark="#FFFFFF">
  <tr class="p9"> 
    <td width="338" height="21" align="center" background="pic/h3.gif"><font color="#FFFFFF" size="+1"><strong>登陆成功！</strong></font></td>
  </tr>
  <tr align="center" class="p9"> 
    <td>&nbsp;</td>
  </tr>
  <tr class="p9"> 
    <td height="17" align="center"><a href="index.asp">恭喜你，你成功登陆！三秒后将自动返回首页</a></td>
  </tr>
  <tr> 
    <td height="18" align="center" class="p9"><a href="index.asp">如果你不想等待，请点击这里</a></td>
  </tr>
  <tr> 
    <td height="18" align="center">&nbsp;</td>
  </tr>
</table>
</body>
</html>
