document.writeln("<table cellspacing=4 cellpadding=0 width=100% border=0>");
document.writeln("  <tr> ");
document.writeln("    <td height=19 width=16%><img src=../pic/magset.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=58>超级兔子</a>(系统工具)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=19 width=16%><img src=../pic/wom.gif width=21></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=57>优化大师</a>(系统工具)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=9 width=16%><b><img src=../pic/fget.gif width=21></b></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=56>FlashGet</a>(下载工具)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td width=16% height=2><img src=../pic/ie.gif width=21 height=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=13>IE ");
document.writeln("      6.0 </a>(网页浏览）</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td width=16% height=2><img src=../pic/fmail.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=59>Foxmail</a>(邮件工具)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td width=16% height=2><img height=17 src=../pic/rar.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=55>WinRAR</a> ");
document.writeln("      (压缩解压)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td width=16% height=2><img src=../pic/amp.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=60>Winamp</a> ");
document.writeln("      (MP3播放)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=8 width=16%><img src=../pic/acd.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=54>ACDSee</a> ");
document.writeln("      (看图工具)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=9 width=16%><img src=../pic/qq.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../qq/software.asp?id=81>OICQ</a> ");
document.writeln("      (聊天寻呼)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=9 width=16%><img src=../pic/suv.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=http://newhua.ruyi.com/down/sth2001xp.zip>超级解霸</a>(视频播放)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=2><img height=20 src=../pic/realone.gif width=20></td>");
document.writeln("    <td background=../pic/a-27.gif><a href=../\"wangruan/software.asp?id=166\">RealONE</a> ");
document.writeln("      (媒体播放)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=2 width=16%><img height=19 src=../pic/bdj.gif width=22></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=../wangruan/software.asp?id=139>中文Real</a>(媒体播放)</td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td height=12 width=16%><img src=../pic/kav.gif width=20></td>");
document.writeln("    <td width=84% background=../pic/a-27.gif><a href=http://hrbftp.soft163.com/iduba2002_new.zip>金山毒霸</a>(病毒查杀)</td>");
document.writeln("  </tr>");
document.writeln("</table>");